remote_theme: samarsault/plainwhite-jekyll
plainwhite:
  name: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: samarsault
    github: samarsault
    linkedIn: in/samarsault # format: locale/username
    
  portfolio_image:  "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  
  sitemap: true
  
  navigation:
    - title: My Work
      url: "/_projects/test1"
    - title: Resume
      url: "/resume"
