name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/
        with:
          args: "-f docx -t gfm "Krajewski - CV.docx" -o "CV.md" # gets appended to pandoc command
