name: Convert .Docx to Markdown

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: | # allows you to break string into multiple lines
            --output=CV.md
            /personal/CV.docx
