name: Convert DocX to Markdown

on:
  push:
    paths:
    - 'CV.docx'

jobs:
  convert_md: 
    runs-on: ubuntu-latest
    steps:
    # We must checkout the latest version of the code to get a copy of all .md files
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1
    - name: Create .DocX
      uses: docker://pandoc/core:latest
      with:
        args: '-f docx "CV.docx" -o CV.md'
      }
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.6.1
      env:
        # The token is built in to actions. No config required.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Add .md files.
        PULL_REQUEST_TITLE: Add .md files.
        PULL_REQUEST_BRANCH: md-add
